name: bonsoir
description: A Zeroconf library that allows you to discover network services and to broadcast your own. Based on Apple Bonjour and Android NSD.
repository: https://github.com/Skyost/Bonsoir/tree/master/bonsoir
issue_tracker: https://github.com/Skyost/Bonsoir/issues
version: 2.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bonsoir_platform_interface: ">=2.0.0 <3.0.0"
  bonsoir_android: ">=2.0.0 <3.0.0"
  bonsoir_darwin: ">=2.0.0 <3.0.0"
  bonsoir_windows:
    path: ../bonsoir_windows

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        default_package: bonsoir_android
      ios:
        default_package: bonsoir_darwin
      macos:
        default_package: bonsoir_darwin
      windows:
        default_package: bonsoir_windows
